### ISSUE TITLE
Password Length Regex Doesn't Work As Intended

### ISSUE THREAD

**Issue by WilsonMcCool** [IFinners/automate-the-boring-stuff-projects#1]
password length regex: `re.compile(r'(.*)+)` will be valid for every length instead of just 8 characters or more. regex should be `re.compile(r'.{8,}')` for desired result.

**Comment by IFinners** [comment]
You're absolutely right. Not sure how I made the mistake back then but you have probably prevented a few others from doing the same with this correction. Very much appreciated.
